#+STARTUP: overview
#+STARTUP: latexpreview
#+TITLE: Thurston norm for non-orientable $3$-manifolds and an application to minimal stretch factors
#+AUTHOR: Sayantan Khan

#+LaTeX_HEADER: \usepackage[extreme]{savetrees}
#+LaTeX_HEADER: \usepackage[utf8]{inputenc}
#+LaTeX_HEADER: \usepackage{mathrsfs}
#+LaTeX_HEADER: \thispagestyle{empty}
#+LaTeX_HEADER: \newcommand{\PGL}{\mathrm{PGL}}
#+LaTeX_HEADER: \newcommand{\RR}{\mathbb{R}}
#+LaTeX_HEADER: \newcommand{\wt}[1]{\widetilde{#1}}
#+OPTIONS: toc:nil

* Introduction

* Background
** The Thurston norm and its applications
** Non-orientable surfaces and $3$-manifolds

* Extending Thurston norm theory for non-orientable $3$-manifolds
On the surface of it, it appears that there isn't a reasonable way to extend the Thurston norm to
non-orientable $3$-manifolds because we require the Thurston norm to be non-zero on embedded
surfaces of negative Euler characteristic.  However, an embedded non-orientable surface of negative
Euler characteristic is $0$ as an element in $H_2(M)$, which means the associated Thurston norm
ought to be $0$. One possible way to get around this is to work with the orientation double cover.
Given a non-orientable $3$-manifold $M$, and an embedded surface $S$ in $M$, one could look at the
orientation double cover $\wt{M}$ and the preimage of $S$ in $\wt{M}$, which we'll call $\wt{S}$.
If $S$ is non-orientable, then $\wt{S}$ is connected, and we can assign $S$ the Thurston norm of
$\wt{S}$. In case $S$ is orientable, it will have two connected components as its preimage. The two
components could very well be negatives of each other in $H_2(M)$, and their sum $0$. To get around
this problem, one could assign the Thurston norm of one of the components of $\wt{S}$ to $S$, but
this description is no longer as elegant as the original description of the Thurston norm.

One gets around this problem by working with cohomology rather than homology. By Poincare duality on
orientable $3$-manifolds, there is a corresponding Thurston norm on $H^1(\wt{M})$. Furthermore,
since there is a covering map from $\wt{M}$ to $M$, we get a map on $H^1$ going the other way. Thus,
given a $1$-form on $M$, one can instead think it's image under the pullback. The following lemma
describes the image and shows that we lose no information when we pull back.

*Lemma*: Let $M$ be a non-orientable $3$-manifold, and $\wt{M}$ its orientation double cover. Let
$\iota: \wt{M} \to \wt{M}$ be the orientation reversing deck transformation, and $p: \wt{M} \to M$
be the covering map. The $p^{\ast}$ maps $H^1(M, \RR)$ bijectively to the $\iota^{\ast}$-invariant
subspace of $H^1(\wt{M}, \RR)$.

*Proof*: Clearly, for any $1$-form $\alpha$ on $M$, $p^{\ast}(\alpha)$ will be $\iota^{\ast}$-invariant.
This means that the image of $p^{\ast}$ lands inside the $\iota^{\ast}$-invariant subspace. To see that
the map is injective at the level of $H^1$ (rather than at the level of $1$-forms), consider a $1$-form
$\alpha$ on $M$ such that $p^{\ast}\alpha$ is exact. We thus have a smooth function $f$ on $\wt{M}$ such
that the following relation holds.
\begin{align*}
df = p^{\ast} \alpha
\end{align*}
But since $p^{\ast}\alpha$ is $\iota^{\ast}$-invariant, we must have $df = \iota^{\ast} df$, and
by pushing the $\iota^{\ast}$ inside, we get that df = d(\iota^{\ast}f). That means $f$ and $\iota^{\ast}f$
differ by a constant, but that constant must be $0$ since $\iota$ is finite order. This shows that $f$ descends
to a function on $M$, and thus $\alpha$ is exact, which proves injectivity of $p^{\ast}$.
Now we show surjectivity. Let $[\alpha]$ be an element in $H^1(\wt{M}, \RR)$ that is $\iota^{\ast}$-invariant.
That means if we pick a $1$-form $\alpha$ in this equivalence class, the following identity holds for some smooth
function $f$.
\begin{align*}
\alpha - \iota^{\ast}(\alpha) = df
\end{align*}
Note that this means $\iota^{\ast}df = -df$. Using these two identities, it's easy to verify that the $1$-form
$\alpha + \frac{df}{2}$ is $\iota^{\ast}$-invariant, and thus in the image of $p^{\ast}$. This proves surjectivity,
and the lemma.

* An application: minimal stretch factors for pseudo-Anosov maps on non-orientable surfaces
