* Style
** Remove contractions
** Remove self judgemental language
For instance, sentences like “this would be more useful if...” should be adapted to “to use in our situation, we will do...”
** Use more formal variants of verbs
I.e., replace "pick" with "choose".
** Fewer quotation marks
If something is “sort of” true, maybe you should say it so that it’s actually true.
** Formula at the end of a sentence
A formula at the end of a sentence should have a period at the end.  There were many cases where you said
“...the following formula.  (Line break) Formula” with no period after the formula.  This should be revised as
“...the following formula: (Line break) Formula.”
** Remove overused instances of "i.e."
There were places where you just used it to restate the beginning of a sentence that weren’t necessary.
** Avoid long sentences
There were a lot of sentences that you split up with clauses separating the flow of the sentence.  I found
these hard to read.
** Prepositions
Points and curves are “in” surfaces, not “on” surfaces.
** Set membership
For example, a sentence might say “fibered faces” when it would be helpful for it to say “fibered faces of
H^1(M,R).”  I can fix most of these (there might be a few places where I’m not sure if you mean H^1 or H_2),
but it’s something to generally be aware of that really helps clarity and mathematical precision.
* Organization
Organizationally, I think Section 3.5 should come before the rest of Section 3 since you consistently use the
fibrations for the version of Poincare duality that you construct.  Perhaps Sections 2/3 should be
restructured as two sections, the first one (new section 2) on mapping class groups of nonorientable surfaces,
including what is currently Section 3.5.  The second section (the new section 3) could be Thurston’s theory on
fibered faces for nonorientable surfaces (beginning with orientable surfaces, current 2.2).
* Section 4
/Remark/: Caleb is handling this right now, so this section will just have the text from the email, until I actually
start working on it.
** Email text
The beginning of Section 4 (including description of Yazdi’s results and statement of yours) should be in the intro.

The notation in Section 4 was confusing.  I think n meant more than one thing, as did k.  But perhaps I’m
wrong.  I also don’t understand the equivalence relation because I’m not sure what type of objects c_{i,j} and
d_{i,j} and likewise r_{i,j} and s_{i,j} are meant to be.

Would it be easier to define \overline{rho}_1 and \overline{\rho}_2 as maps on the comments of T_\infinity?
Or maybe T_\infinity is connected?  I’m not actually sure what T_\infinity is (in part because I think you
defined it as S_\infinity, in part because I don’t understand the equivalence relation).  Also, is the n used
to define P_{n,k} the number of punctures?  I’m guessing so.  It might be helpful to remind us of this (or
maybe you did and I was distracted by other confusing things).

At the bottom of page 20/top of 21 did you mean “consistent” when you kept referring to “inconsistent”
intersections?

What’s the conclusion of Lemma 4.6?  It looks like a definition to me.  Is the point that the k used in Lemma
4.6 is the same k as the construction?

I don’t understand the relevance of Lemma 4.6 to the statements at the end of the proof of Lemma 4.7.  Lemma
4.6 says nothing about dilatations.
